USE [master]
GO
/****** Object:  Database [FitnessClubs]    Script Date: 29.06.2026 19:49:01 ******/
CREATE DATABASE [FitnessClubs]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FitnessClubs', FILENAME = N'C:\Users\Арина\FitnessClubs.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FitnessClubs_log', FILENAME = N'C:\Users\Арина\FitnessClubs_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FitnessClubs].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FitnessClubs] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FitnessClubs] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FitnessClubs] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FitnessClubs] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FitnessClubs] SET ARITHABORT OFF 
GO
ALTER DATABASE [FitnessClubs] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [FitnessClubs] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FitnessClubs] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FitnessClubs] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FitnessClubs] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FitnessClubs] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FitnessClubs] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FitnessClubs] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FitnessClubs] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FitnessClubs] SET  ENABLE_BROKER 
GO
ALTER DATABASE [FitnessClubs] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FitnessClubs] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FitnessClubs] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FitnessClubs] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FitnessClubs] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FitnessClubs] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FitnessClubs] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FitnessClubs] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FitnessClubs] SET  MULTI_USER 
GO
ALTER DATABASE [FitnessClubs] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FitnessClubs] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FitnessClubs] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FitnessClubs] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FitnessClubs] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FitnessClubs] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FitnessClubs] SET QUERY_STORE = ON
GO
ALTER DATABASE [FitnessClubs] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [FitnessClubs]
GO
/****** Object:  Table [dbo].[Branches]    Script Date: 29.06.2026 19:49:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Branches](
	[branch_id] [int] IDENTITY(1,1) NOT NULL,
	[branch_name] [nvarchar](100) NOT NULL,
	[address] [nvarchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[branch_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Classes]    Script Date: 29.06.2026 19:49:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Classes](
	[class_id] [int] IDENTITY(1,1) NOT NULL,
	[class_name] [nvarchar](100) NOT NULL,
	[trainer_id] [int] NOT NULL,
	[branch_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[class_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 29.06.2026 19:49:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[client_id] [int] IDENTITY(1,1) NOT NULL,
	[full_name] [nvarchar](150) NOT NULL,
	[phone] [nvarchar](20) NULL,
	[birth_date] [date] NULL,
	[registration_date] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[client_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Memberships]    Script Date: 29.06.2026 19:49:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Memberships](
	[membership_id] [int] IDENTITY(1,1) NOT NULL,
	[client_id] [int] NOT NULL,
	[membership_type] [nvarchar](50) NOT NULL,
	[start_date] [date] NOT NULL,
	[end_date] [date] NOT NULL,
	[price] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[membership_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Trainers]    Script Date: 29.06.2026 19:49:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Trainers](
	[trainer_id] [int] IDENTITY(1,1) NOT NULL,
	[full_name] [nvarchar](150) NOT NULL,
	[specialization] [nvarchar](100) NULL,
	[branch_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[trainer_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Visits]    Script Date: 29.06.2026 19:49:01 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Visits](
	[visit_id] [int] IDENTITY(1,1) NOT NULL,
	[client_id] [int] NOT NULL,
	[class_id] [int] NULL,
	[visit_date] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[visit_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Classes]  WITH NOCHECK ADD FOREIGN KEY([branch_id])
REFERENCES [dbo].[Branches] ([branch_id])
GO
ALTER TABLE [dbo].[Classes]  WITH NOCHECK ADD FOREIGN KEY([trainer_id])
REFERENCES [dbo].[Trainers] ([trainer_id])
GO
ALTER TABLE [dbo].[Memberships]  WITH NOCHECK ADD FOREIGN KEY([client_id])
REFERENCES [dbo].[Clients] ([client_id])
GO
ALTER TABLE [dbo].[Trainers]  WITH NOCHECK ADD FOREIGN KEY([branch_id])
REFERENCES [dbo].[Branches] ([branch_id])
GO
ALTER TABLE [dbo].[Visits]  WITH NOCHECK ADD FOREIGN KEY([class_id])
REFERENCES [dbo].[Classes] ([class_id])
GO
ALTER TABLE [dbo].[Visits]  WITH NOCHECK ADD FOREIGN KEY([client_id])
REFERENCES [dbo].[Clients] ([client_id])
GO
USE [master]
GO
ALTER DATABASE [FitnessClubs] SET  READ_WRITE 
GO
